Duplicate inputs and adding more input fields
cci-toast/frontend pull request #190
Opened 2020-05-02 18:24 UTC by pinkdragon1000

2020-05-02 22:14 UTC, msd96drexel requested changes

2020-05-02 22:14 UTC, msd96drexel commented on frontend/src/components/page_content/plan-content.js
> +  getSalaryAfterTaxValue,
what's the reason for renaming to include "value" at the end? i would think it's kinda redundant

2020-05-02 22:14 UTC, msd96drexel commented on frontend/src/components/page_content/profile/family.js
> +//export default Family;
this comment should be deleted

2020-05-02 22:14 UTC, msd96drexel commented on frontend/src/components/toast/toast-duplicate-button.js
> +      <div>
can this wrapping div be changed to <React.Fragment>?

2020-05-02 22:14 UTC, msd96drexel commented on frontend/src/components/toast/toast-duplicate-button.js
> +    const updateChildrenWithProps = (idx, d) => {
i dont understand what idx and d mean, can they be renamed to something more useful?

2020-05-02 22:14 UTC, msd96drexel commented on frontend/src/redux/actions.js
> +export const addGoal = (value) => ({
what is value here? the goal object or description? a better variable name would help me understand more

2020-05-02 22:14 UTC, msd96drexel commented on frontend/src/redux/actions.js
> +export const setSalaryAfterTaxValue = (valueName, value) => ({
can we just name this 'setSalaryAfterTax'?

for all the selectors and actions with 'value' at the end and its just one value you're changing- can we rename these to exclude value at the end cuz its redundant? if it interferes with an existing selector or action for plan maybe the plan selectors should have 'plan' added on to the end, if possible

2020-05-02 22:14 UTC, msd96drexel commented on frontend/src/redux/actions.js
> +export const addRetirement = (value) => ({
for all the ones with 'value' as the param and they only change one value, can we make the word more clear for what the value is? like 'retirement' for this case probably. the ones i made with 'value' take in many different possible values, so i just used the word 'value' as a general term

2020-05-02 22:14 UTC, msd96drexel commented on frontend/src/redux/reducers/family.js
> +      const { value } = action.payload;
same thing here about 'value' in the reducers, a more descriptive name when just changing one value would be more informative

2020-05-02 22:14 UTC, msd96drexel commented on frontend/src/redux/reducers/finances.js
> +  utility: [],
why is this an array? i thought we were only asking for one value amount for utilities? same for some of the other fields

2020-05-02 22:14 UTC, msd96drexel commented on frontend/src/redux/reducers/finances.js
> -    case "setFinancesValue": {
why not just have setFinancesValue and pass in the value name you want to change? i do this for the other reducers too so you can use it to set other stuff. then you have an action for setting a list value too. then you don't need to create a bunch of actions to set each individual one, just pass in the one you want to change as a parm. i have this logic set up in redux for most reducers

2020-05-02 22:14 UTC, msd96drexel commented on frontend/src/redux/reducers/goals.js
> +      var tempGoals = [...state.goals];
can you use 'let' instead of 'var' for a more restrictive scope here?

2020-05-02 22:14 UTC, msd96drexel commented on frontend/src/components/toast/toast-duplicate-button.js
> +    console.log("value:", this.props.value);
we don't want to leave these console.log in here

2020-05-02 22:14 UTC, msd96drexel commented on frontend/src/components/toast/toast-duplicate-button.js
> +    event.preventDefault();
what is the purpose of event.preventDefault() here?

2020-05-02 22:14 UTC, msd96drexel commented on frontend/src/components/toast/toast-duplicate-button.js
> +    if (this.props.maxItems && this.props.maxItems <= this.props.value.length)
can you add { } around the if's here for better readability?

2020-05-02 22:14 UTC, msd96drexel commented on frontend/src/components/toast/toast-duplicate-button.js
> +      return React.Children.map(this.props.children, (child, i) => {
you can get rid of the {} and return and just have => React.cloneElement ... as a shorthand

2020-05-02 22:14 UTC, msd96drexel commented on frontend/src/components/toast/toast-input.js
> +            value={this.props.value || ""}
defaultValue was used to solve a bug before about not being able to type into the fields. did you specifically test for that when you changed this? and what's the reason for changing this?

2020-05-08 02:34 UTC, pinkdragon1000 commented on frontend/src/components/toast/toast-duplicate-button.js
> +      <div>
For some reason when I tried to change to React.Fragment here it broke the page

2020-05-08 14:48 UTC, msd96drexel requested changes

2020-05-08 14:48 UTC, msd96drexel commented on frontend/src/components/toast/toast-duplicate-input-button.js
> +    .hideBtn{
can you make this hide-btn (consistency between css)

2020-05-08 14:48 UTC, msd96drexel commented on frontend/src/components/toast/toast-show-hide-input.js
> +    let checkEmpty = React.Children.map(this.props.children, (child, i) => {
you can shorthand this to => !!child.props.value (remove the {} and return)

2020-05-08 14:48 UTC, msd96drexel commented on frontend/src/components/toast/toast-show-hide-input.js
> +    for (var x of checkEmpty) if (x) result = false;
can you put {} around the for and if for better readability?

2020-05-08 14:48 UTC, msd96drexel commented on frontend/src/components/toast/toast-show-hide-input.js
> +    .hide{
can you add spaces around the css where needed for better readability and consistency between our css?

2020-05-08 14:48 UTC, msd96drexel commented on frontend/src/redux/actions.js
> +export const setFinances = (valueName, value) => ({
i think this one should have value at the end cuz its to change a general value in finances state

2020-05-08 14:48 UTC, msd96drexel commented on frontend/src/components/toast/toast-duplicate-input-button.js
> +/*Expects an array and duplicates the "children".  Set maxItems to limit the number of duplicates.
can you put a space after the /* for better readability

2020-05-08 14:48 UTC, msd96drexel commented on frontend/src/components/toast/toast-duplicate-input-button.js
> +    let classes = "";
change this to classes = [] and push hideBtn to the array. then return classes.join(' '). this is what i typically do. it makes it easier to add more classes later if you need them

2020-05-08 14:48 UTC, msd96drexel commented on frontend/src/components/toast/toast-duplicate-input-button.js
> +    if (this.props.maxItems && this.props.maxItems <= this.props.value.length)
can you put {} around these ifs for better readability

2020-05-08 14:48 UTC, msd96drexel commented on frontend/src/components/page_content/profile/goals.js
> +            onChange={this.setGoalListValue}
i dont think you need this onChange because ToastDuplicateInputButton might handle it?

2020-05-08 15:08 UTC, msd96drexel approved these changes

2020-05-08 15:08 UTC, merged